services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file:
      - projeto22-autoral-back-end/.env
    volumes:
       - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./projeto22-autoral-back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - projeto22-autoral-back-end/.env

  next:
    container_name: next
    build: ./projeto22-autoral-front-end
    ports:
      - 3000:3000
    volumes:
      - next-volume:/var/www/html

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - next-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - next

volumes:
  postgres-volume:
  next-volume: