services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file:
      - projeto22-autoral-back-end/.env
    volumes:
       - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./projeto22-autoral-back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - projeto22-autoral-back-end/.env

volumes:
  postgres-volume: