import './globals.css';
import { Roboto } from 'next/font/google';
import Header from '@/app/components/header';
import Providers from './contexts';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
        <Providers>
          <Header />
        </Providers>
        {children}
      </body>
    </html>
  )
}