import './globals.css';
import { Roboto } from 'next/font/google';
import Header from '@/components/Header';
import Providers from '@/contexts';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.className} min-h-[100vh]`}>
        <Providers>
          <Header />

          <main className='flex justify-center'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}