name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-Github:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envflie
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: 5000
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "fibra_colada_test"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/fibra_colada_test"
          envkey_JWT_SECRET : "secret"
          directory: projeto22-autoral-back-end
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node npm run test